// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT-38peY2sWXYbIqy9ISAYLjVpg_Wx3Fs',
    appId: '1:210209662966:web:53cf0116559bef331d49d7',
    messagingSenderId: '210209662966',
    projectId: 'code-assist-4d344',
    authDomain: 'code-assist-4d344.firebaseapp.com',
    storageBucket: 'code-assist-4d344.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-CLhfyqsL0DIiXe2SJ7uKcJBL0HwL_ms',
    appId: '1:210209662966:android:dd2d58571e76e1e61d49d7',
    messagingSenderId: '210209662966',
    projectId: 'code-assist-4d344',
    storageBucket: 'code-assist-4d344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk4pz13w0DuVxa1vWTQhGjTbml8NR6r3A',
    appId: '1:210209662966:ios:445039f6ec5d581a1d49d7',
    messagingSenderId: '210209662966',
    projectId: 'code-assist-4d344',
    storageBucket: 'code-assist-4d344.appspot.com',
    iosClientId:
        '210209662966-bvgb6lusb2dsjkjk3jgaial9slsgdqar.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeAssist',
  );
}
